apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: node171766578 
  janus-idp.io/tekton: node171766578
  backstage.io/kubernetes-id: node171766578
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node171766578
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  